GET http://127.0.0.1:8000/books/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTYwODc2MzcsInN1YiI6IjZETFZKUHF2VDkifQ.9fFeMnFk10gmk3hBhxJl-PaOUnz9nTjZ1FV6n88904o