PATCH http://127.0.0.1:8000/books/1 HTTP/1.1
content-type: application/json

{
    "title": "self-teaching-PHP",
    "remark": "test",
    "img_url": "https://ebookstore.sony.jp/photo/LT00014922/LT000149223001280076_XLARGE.jpg"
}