POST http://127.0.0.1:8000/studying-books/1/record HTTP/1.1
content-type: application/json

{
    "target_complate_items": [
        {
            "id": 1,
            "is_completed": true
        },
        {
            "id": 2,
            "is_completed": true
        },
        {
            "id": 11,
            "is_completed": true
        }
    ],
    "study_minutes": 100
}